title: Stencil
email: hi@ionic.io
description: > # this means to ignore newlines until "baseurl:"
  Stencil makes it easy to build powerful, reusable web components that run everywhere
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: stenciljs

# Build settings
markdown: kramdown
